In [3]:
import numpy as np

In [29]:
class queue():
    def __init__(self,size):
        self.size= size
        self.front=-1
        self.rear=-1
        self.q= np.zeros([size],dtype='int')

    def insert(self,value):
        if self.rear== self.rear-1:
            print("Queue is full")

        elif self.front==-1:
            self.front==0
        self.rear+=1    
        self.q[self.rear]=value
        return value

    def delete(self,value):
        if self.front== -1:
            print('Queue is Empty')
            return
        value = self.q[self.front]    
        if self.front==self.rear:
            self.front== self.rear==-1 
        else:
            self.front+=1 
        return value       
        



In [30]:
q= queue(5)
q.size

5

In [31]:
print(q.front)
print(q.rear)
print(q.q)

-1
-1
[0 0 0 0 0]


In [32]:
q.insert(4)
print(q.q)
print(q.front)
print(q.rear)

[4 0 0 0 0]
-1
0


In [19]:
q.insert(12)
print(q.q)

[ 4 12  0  0  0]


In [20]:
print(q.rear)
print(q.front)

1
-1


In [12]:
q.insert(2)
print(q.q)

[10  1  4 12  2]


In [13]:
print(q.rear)
print(q.front)

4
-1


In [14]:
q.delete(12)
print(q.q)
print(q.front)
print(q.rear)

Queue is Empty
[10  1  4 12  2]
-1
4
