In [29]:
import numpy as np

In [30]:
class stack:
    def __init__(self,size):
        self.size= size
        self.stackarea= np.zeros([size],dtype='int')
        self.tos=-1

    def push(self,value):
        if self.tos== self.size-1:
            print('Stack overflow')
            return
        else:
            self.tos+=1
            self.stackarea[self.tos]=value

    def pop(self,value):
        if self.tos== -1:
            print("Stack is empty")
        else:
            value = self.stackarea[self.tos]
            self.tos-=1
            return value

    def peep(self,k):
        if k<0 and self.tos-k+1<0:
            print("Stack is empty")
        else:
            value= self.stackarea[self.tos-k+1]
            return value

    def change(self,k,n_value):
        if k<0 and self.tos-k+1<0:
          print("Stack is empty") 

        else:
            self.stackarea[self.tos-k+1]= n_value
        return n_value                                     

In [31]:
st= stack(5)
print(st.size)
print(st.tos)
st.stackarea

5
-1


array([0, 0, 0, 0, 0])

In [32]:
st.push(10)
print(st.tos)
st.stackarea

0


array([10,  0,  0,  0,  0])

In [33]:
st.push(12)
print(st.tos)
st.stackarea

1


array([10, 12,  0,  0,  0])

In [34]:
st.push(14)
print(st.tos)
st.stackarea

2


array([10, 12, 14,  0,  0])

In [35]:
st.push(16)
print(st.tos)
st.stackarea

st.push(18)
print(st.tos)
st.stackarea

st.push(20)
print(st.tos)
st.stackarea

3
4
Stack overflow
4


array([10, 12, 14, 16, 18])

In [36]:
st.pop(10)

print(st.tos)
st.stackarea

3


array([10, 12, 14, 16, 18])

In [37]:
st.peep(2)

14

In [38]:
st.change(2,15)
st.stackarea

array([10, 12, 15, 16, 18])

In [62]:
class stack:
    def __init__(self,size):
        self.size= size
        self.stackarea= np.zeros([size],dtype='int')
        self.tos=-1

    def push(self,value):
        if self.tos== self.size-1:
            temp= np.zeros([2*self.size],dtype='int')
            for i in range(self.size):
                temp[i]= self.stackarea[i]
            self.stackarea= temp
            self.size= 2*self.size  
        self.tos+=1 
        self.stackarea[self.tos]=value     
        return value
        

    def pop(self,value):
        if self.tos== -1:
            print("Stack is empty")
        else:
            value = self.stackarea[self.tos]
            self.tos-=1

            if self.tos<self.size/2:
              temp= np.zeros([self.size/2],dtype='int')
              for i in range(self.size+1):
                temp[i]= self.stackarea[i]
              self.stackarea= temp
              self.size= int(self.size/2)     
            return value

    def peep(self,k):
        if k<0 and self.tos-k+1<0:
            print("Stack is empty")
        else:
            value= self.stackarea[self.tos-k+1]
            return value

    def change(self,k,n_value):
        if k<0 and self.tos-k+1<0:
          print("Stack is empty") 

        else:
            self.stackarea[self.tos-k+1]= n_value
        return n_value                                     

In [50]:
st1=stack(5)


In [51]:
st1.size

5

In [57]:
st1.push(72)

st1.stackarea

array([12, 24, 36, 48, 60, 72,  0,  0,  0,  0])

In [64]:
st1.pop(72)
st1.stackarea

TypeError: 'float' object cannot be interpreted as an integer